### ISSUE TITLE
proje ismi hakkında

### ISSUE THREAD

**Issue by dnomak** [baransomakli/flexiblegs-sample#1]
Repo adındaki F ve S harfleri küçük olsa daha iyi olabilir :) Aşağıdaki linkleri bir incele istersen. Diğer Github organizasyonları ve repolarıda inceleyebilirsin ama yinede tercih meselesi tabi :)

https://en.wikipedia.org/wiki/CamelCase
https://en.wikipedia.org/wiki/Snake_case

**Comment by baransomakli** [comment]
Dediğin şeyleri düzenledim :)

**Comment by dnomak** [comment]
teşekkürler :)
